name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  NEXT_PUBLIC_APP_URL: ${{ vars.NEXT_PUBLIC_APP_URL }}
  NEXT_PUBLIC_ENABLE_INDEXING: ${{ vars.NEXT_PUBLIC_ENABLE_INDEXING }}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check types
        run: pnpm type-check

      - name: Check lint
        run: pnpm lint

      - name: Check format
        run: pnpm format-check

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build
